### PR TITLE
Feature/logout confirm

### PR DESCRIPTION
**Pull request by zingelst**
- Added dialog to confirm a logout and if the user chooses, to not ask again.
- Added option in settings to allow user to disable logout confirm dialog or to turn it back on
- Removed a random duplicate import in feedback.dart

Needs testing on iOS

### CODE REVIEW

**Review by jpward — COMMENTED** [review]
For IOS no matter what I select I always see the confirm page I'm assuming Android doesn't have this problem?

**Comment by zingelst** [comment]
That's the idea, after you select "Don't ask again", you should be able to log in/out without the dialog. Do SharedPreferences work differently on iOS vs Android? That's where the config val is stored and checked against to determine if the dialog should be shown or not.

**Comment by jpward** [comment]
I just fired up the Android simulator and I have the same problem, I see the confirm page no matter how I set the slide bar.

**Comment by jpward** [comment]
Ah, I don't see a prefs.setBool in bottom_app_bar.dart only in settings.  You will need to check user settings on logout and call setBool

**Comment by zingelst** [comment]
Added the setBool to bottom_app bar per review. Can you confirm?

**Pull request merged**
